### ISSUE TITLE
"?"

### ISSUE THREAD

**Issue by armync** [OciXCrom/ChatManager#1]
When I type a message I get "?" before the name. I set <country> at the beggining and as I saw it says that if I get "?" geoip don't detect the country?.. Why? How I get the error in order to fix this? I wana say that I have the latest GEOIP version :)

**Comment by OciXCrom** [comment]
If you're testing the plugin on a local server, geoip will always fail to detect the location thus displaying "?" as an error.

**Comment by armync** [comment]
Ok, I got it
