### ISSUE TITLE
The color code cannot be displayed properly

### ISSUE THREAD

**Issue by ghost** [OciXCrom/ChatManager#11]
After upgrading to the latest Commit version, the color code is invalid.

**Comment by OciXCrom** [comment]
Which color code? Explain.

**Comment by ghost** [comment]
Every code, like [Chat Colors], and the prefix color of the crx_nonamechange.amxx tip is also invalid.

**Comment by OciXCrom** [comment]
What do you mean by "invalid"? You're making me pull words out of your mouth. Provide a screenshot if you can't explain.

**Comment by ghost** [comment]
I mean, TIP is displayed, but the color of TIP is gone, only the default color (yellow) is displayed.
The chat is also displayed, the prefix is displayed, but there is no color (only yellow).
The key issue is that there is no problem with the old version.

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/70419030/110880093-07032600-8319-11eb-93d7-02accdb9cdcd.png)
![2](https://user-images.githubusercontent.com/70419030/110880098-0a96ad00-8319-11eb-8763-1e2fb3f4d137.png)

**Comment by ghost** [comment]
I think that is "CromChat.inc"'s problem. And I found that my RankSystems never showed colors...I'm using AMX Mod X 1.9.0.5271 and Metamod-R, ReGameDLL + ReHLDS latest version, for GoldSource Build 8684 (CZ).

**There is nothing wrong with SimpleMenu (I mean TIP color text), because you haven't updated it recently. So I think some recent updates crashed the color display. It should be the problem of CromChat.**

**Comment by OciXCrom** [comment]
What is TIP?

I updated CromChat not to show colors if used in any game other than Counter-Strike. Does CZ also support the same colors? If so, I wasn't aware of this.

Try compiling with this one and tell me if the colors work - https://pastie.io/enffig.m

**Comment by ghost** [comment]
YES, sir, CZ also support the same color.
Oh, https://pastie.io/enffig.m worked!!!

**Comment by OciXCrom** [comment]
Got it. Thank you for letting me know. I will update the .inc file when I get home.

**Comment by ghost** [comment]
You're welcome, sir. Looking forward to your update. Your plug-in is of great help to my server. I used your 12 plug-ins, they make my server look very professional.
**:)**

**Comment by OciXCrom** [comment]
Glad you enjoy my work. I also updated `crx_ranksystem.sma` to support colors in CZ. Download and recompile it to enable colors for it as well.
