### ISSUE TITLE
Conflict with other chat plugins

### ISSUE THREAD

**Issue by AliNemati13** [OciXCrom/ChatManager#12]
I'm using Simple Swear Filter [ [Link](https://forums.alliedmods.net/showthread.php?t=1404) ]
To replaces the chat messages containing any swear word but i have a problem with ChatManager
i receive double chat messages, filtered and not filtered

![Screen](https://user-images.githubusercontent.com/37639464/112696576-bb698400-8ea3-11eb-9303-ae5e287e66f2.png)

i changed SAY_METHOD to 1 for testing purpose but i receive double filtered chat messages

![Screen 2](https://user-images.githubusercontent.com/37639464/112697092-8ad61a00-8ea4-11eb-9a6a-4a3f30fefa04.png)

My idea is add swear filter list and whitelist option to ChatManager

**Comment by OciXCrom** [comment]
If that 2004 plugin is made properly, it will work with this one if you put it above crx_chatmanager in plugins.ini in conjuction with SAY_METHOD = 1.

If it doesn't, the problem is from the plugin, not mine. On my phone right now so I haven't seen its code.

**Comment by AliNemati13** [comment]
I put it above crx_chatmanager and set SAY_METHOD to 1 but this happened
when i'm alone in server it's seems okay

![3](https://user-images.githubusercontent.com/37639464/112728293-1fdc2000-8f44-11eb-9854-4be4600b8083.png)

but when somebody joins in server this will happen, i receive double text chats

![4](https://user-images.githubusercontent.com/37639464/112728312-36827700-8f44-11eb-822f-216c8d95896c.png)
![5](https://user-images.githubusercontent.com/37639464/112728325-4ac67400-8f44-11eb-9959-c309dcef144c.png)

can you add swear filter option to your plugin ?

**Comment by OciXCrom** [comment]
I reviewed the code of the plugin you're using and it's terrible. It uses a very wrong way to censor messages. It doesn't even block the original message thus resulting in my plugin catching it as well.

Please switch to a better plugin that does the job properly. There's no point in me adding something like that to mine when many already exist and can work together.

**Comment by AliNemati13** [comment]
Yeah, sure.
What do you offer for a better plugin ?

**Comment by OciXCrom** [comment]
I haven't personally used such plugins so I can't really recommend any. Search around, I'm sure there are some good ones nowadays.
