### ISSUE TITLE
Problem after upgrading to AMXX 1.9.0 build 5229

### ISSUE THREAD

**Issue by regener** [OciXCrom/ChatManager#4]
Hey, I just updated everything that is on my server to the latest versions.
Everything works fine except ChatManager, that gives me this error:

> L 10/02/2018 - 07:32:43: Log file started (file "cstrike/addons/amxmodx/logs/chatmanager_errors.log") (game "cstrike") (amx "1.9.0.5229")
L 10/02/2018 - 07:32:43: Line 11: Format definition "1" doesn't exist.
L 10/02/2018 - 07:32:43: Line 14: Format definition "b" doesn't exist.
L 10/02/2018 - 07:32:43: Line 17: Format definition "@," doesn't exist.
L 10/02/2018 - 07:32:43: Line 19: Format definition "*Halott*" doesn't exist.
L 10/02/2018 - 07:32:43: Line 20: Format definition "*Halott*" doesn't exist.
L 10/02/2018 - 07:32:43: Line 21: Format definition "(Terrorist)" doesn't exist.
L 10/02/2018 - 07:32:43: Line 22: Format definition "(Counter-Terrorist)" doesn't exist.
L 10/02/2018 - 07:32:43: Line 23: Format definition "(Néző)" doesn't exist.
L 10/02/2018 - 07:32:43: Line 26: Format definition "?" doesn't exist.
L 10/02/2018 - 07:32:43: Line 29: Format definition "%X" doesn't exist.
L 10/02/2018 - 07:32:43: Line 34: Format definition "%dead_prefix%" doesn't exist.
L 10/02/2018 - 07:32:43: Line 35: Format definition "%dead_prefix%" doesn't exist.
L 10/02/2018 - 07:32:43: Line 61: Invalid info type: b
L 10/02/2018 - 07:32:43: Line 67: Invalid info type: b

Can I request some help? :D

**Comment by OciXCrom** [comment]
Looks like something went wrong in your ChatManager.ini file. Attach it or its contents so I can have a look. I'm using the plugin on AMXX 1.10.0 build 5233 and it doesn't have any problems.

**Comment by regener** [comment]
Oh hell, I haven't updated the .ini to the new formats and stuff, that must be it.
Sorry for that, doing it right now.
