### ISSUE TITLE
Idea: admin only chat mode with a command to trigger it

### ISSUE THREAD

**Issue by regener** [OciXCrom/ChatManager#5]
As the title says it :D
The admin level would be set in the ini file and only messages from users with that flag would displayed if enabled. Also announce it as "Admin only mode is enabled" to chat.

**Comment by OciXCrom** [comment]
It's a good idea, but this can be made with any other plugin at the moment. It doesn't need to be incorporated in the main plugin since a new plugin can be made and they can work together without any problems.
