### ISSUE TITLE
Change name twice

### ISSUE THREAD

**Issue by hardixnph** [OciXCrom/ChatManager#9]
Hello, when someone change their name the message 'Player has changed his name to Player2' appears twice

**Comment by OciXCrom** [comment]
This plugin has nothing to do with the name change message. Your problem is coming from somewhere else.

**Comment by hardixnph** [comment]
And you know from what plugin?... because I'm so pissed, I post a screenshot of plugins.ini?

**Comment by OciXCrom** [comment]
The screenshot doesn't allow me to view the plugins' codes. I can only judge by their names which might not be helpful.
It should be a plugin that modifies the "SayText" message. Search for that in the .sma files.
Try disabling plugins 1 by 1 until the problem stops.

How did you decide that it's this plugin that's causing the issue?

**Comment by hardixnph** [comment]
One guy said me that to put chatmanager.amxx in top of the plugins, i have advanced_bans_sql.amxx and chatmanager.amxx, is this ok? Thanks for reply!

**Comment by OciXCrom** [comment]
The location in plugins.ini does not matter.
I don't see how Advanced Bans is related to Chat Manager.

**Comment by hardixnph** [comment]
Is not related, but some people say that I need to put Chat Manager on the top of all plugins.

I have something with SayText but is this: gmsgSayText = get_user_msgid("SayText");

**Comment by OciXCrom** [comment]
If it's not related, I don't see why you're asking for help here out of all places.
Like I said, the position in plugins.ini does not matter.

You need to look for `register_message` with `SayText`.

**Comment by hardixnph** [comment]
I don't have a plugin with that function in it.
